enabled: true
allow-visit : true
players:
texts:
  welcome:
    fore-regin: Welcome. Please use /erodlogin reg <password> <password> to register into Tribina.
    fore-login: Welcome back. Please use /erodlogin <password> to log into Tribina.
    post-login: Welcome to Tribina.
  function-enable: Erod LogIn enabled.
  function-disable: Erod LogIn disabled.
  function-failed: You cannot set the enability. It may because that you are not an op, or you have not login.
  visit-allow: Visit allowed.
  visit-deny: Visit denied.
  visit-failed: You cannot set the visibility. It may because that you are not an op, or you have not login.
  reg-accept: Your register accepted.
  reg-denied: Your register failed. It may because that you have already registered, or you are not a player, or the system is not enabled.
  login-accept: Your login accepted.
  login-denied: Your login denied.
  login-error: Your login failed. It may because that you are not a player, or you have already logged in, or the system is not enabled.
  login-wait: Your login is too frequent, please wait $time$ seconds.