enabled: true
default-range: 20
players:
texts:
  function-enable: Erod RangeTalk enabled.
  function-disable: Erod RangeTalk disabled.
  set-range: Player $player$'s talk range is set to $range$.
  set-range-fail: Player talk range set failed. It may because you are not an op, or the range is not a number, or the player does not exist.
  set-can-shout-accept: Player $player$ can shout now.
  set-can-shout-deny: Player $player$ cannot shout now.
  set-can-shout-fail: Player shout set failed. It may because you are not an op, or the value is not a boolean, or the player does not exist.
  shout-fail: You cannot shout.