enabled: true
default-range: 20
players:
texts:
  function-enable: Erod RangeTalk enabled.
  function-disable: Erod RangeTalk disabled.
  set-range-accept: Player $player$'s talk range is set to $range$.
  set-range-failed: Player talk range set failed. It may because you are not an op, or the range is not a number, or the player does not exist.
  set-can-shout-true: Player $player$ can shout now.
  set-can-shout-false: Player $player$ cannot shout now.
  set-can-shout-failed: Player shout set failed. It may because you are not an op, or the value is not a boolean, or the player does not exist.
  shout-failed: You cannot shout.